"""Shared pytest fixtures for larkin-mcp tests.

WARNING: Most of the test suite was generated by AI so just a heads up."""

import json
from pathlib import Path

import pytest


@pytest.fixture
def tool_contracts() -> dict:
    """Load the tool contracts JSON for contract validation tests."""
    contracts_path = Path(__file__).parent.parent.parent / "resources" / "test-fixtures" / "tool-contracts.json"
    with open(contracts_path) as f:
        return json.load(f)


@pytest.fixture
def resource_schema() -> dict:
    """Load the resource schema JSON for validation tests."""
    schema_path = Path(__file__).parent.parent.parent / "resources" / "schemas" / "resource.schema.json"
    with open(schema_path) as f:
        return json.load(f)
