"""
Tests for utility functions in src/util/resources.py.

WARNING: Most of the test suite was generated by AI so just a heads up.
"""

from src.util.resources import list_resources, load_resource, search_resources


class TestLoadResource:
    """Tests for load_resource function."""

    def test_load_resume(self):
        """Test loading the resume resource."""
        content = load_resource("resume")
        assert "John Larkin" in content
        assert not content.startswith("Resource '")

    def test_load_bio(self):
        """Test loading the bio resource."""
        content = load_resource("bio")
        assert content
        assert not content.startswith("Resource '")

    def test_load_skills(self):
        """Test loading the skills resource."""
        content = load_resource("skills")
        assert content
        assert not content.startswith("Resource '")

    def test_load_projects(self):
        """Test loading the projects resource."""
        content = load_resource("projects")
        assert content
        assert not content.startswith("Resource '")

    def test_load_contact(self):
        """Test loading the contact resource."""
        content = load_resource("contact")
        assert content
        assert not content.startswith("Resource '")

    def test_load_nonexistent_resource(self):
        """Test loading a resource that doesn't exist."""
        content = load_resource("nonexistent_resource_xyz")
        assert content.startswith("Resource '")
        assert "not found" in content.lower()


class TestListResources:
    """Tests for list_resources function."""

    def test_returns_list(self):
        """Test that list_resources returns a list."""
        resources = list_resources()
        assert isinstance(resources, list)

    def test_contains_expected_resources(self):
        """Test that common resources are in the list."""
        resources = list_resources()
        expected = ["resume", "bio", "skills", "projects", "contact"]
        for resource in expected:
            assert resource in resources, f"Expected '{resource}' to be in resources"

    def test_no_empty_entries(self):
        """Test that there are no empty entries."""
        resources = list_resources()
        for resource in resources:
            assert resource, "Empty resource name found"


class TestSearchResources:
    """Tests for search_resources function."""

    def test_search_finds_matches(self):
        """Test that search finds matching content."""
        results = search_resources("Python")
        assert len(results) > 0, "Expected to find 'Python' in at least one resource"

    def test_search_case_insensitive(self):
        """Test that search is case-insensitive."""
        results_lower = search_resources("python")
        results_upper = search_resources("PYTHON")
        # Both should find results
        assert len(results_lower) > 0
        assert len(results_upper) > 0

    def test_search_no_matches(self):
        """Test search with no matches."""
        results = search_resources("xyznonexistentterm123")
        assert len(results) == 0

    def test_search_returns_dict(self):
        """Test that search returns a dictionary."""
        results = search_resources("test")
        assert isinstance(results, dict)

    def test_search_results_are_lists(self):
        """Test that search result values are lists of strings."""
        results = search_resources("Python")
        for resource, lines in results.items():
            assert isinstance(resource, str)
            assert isinstance(lines, list)
            for line in lines:
                assert isinstance(line, str)
